name: agora_live_video_call
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  agora_rtc_engine: ^5.3.0
  flutter:
    sdk: flutter
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  # - assets/img
  #   - images/a_dot_ham.jpeg
